### ISSUE TITLE
IntArray type not listed in assignment 6

### ISSUE THREAD

**Issue by TimvdLippe** [TUDelft-IN4303-2016/TUDelft-IN4303-2016.github.io#12]
In assignment 6 we have to write tests that invoke the strategy `get-type` which returns one of several types. However, the assignment does not list the type used for int arrays in the (reference) implementation. It only lists `Int()`, `Bool` and `ClassType`, but what is the exact syntax for `int[]`? I would expect `IntArray()`, but just want to be sure.

**Comment by martijndwars** [comment]
That's correct; you can also find this in the signature file. It used to be impossible to test int arrays (due to problems in spt), but we've fixed that in this year's edition. I'll update the assignment, thanks for reporting.

**Comment by martijndwars** [comment]
Fixed in [985a333f3385bd82e0c25a3b00ca8fec12d44062](https://github.com/TUDelft-IN4303-2016/TUDelft-IN4303-2016.github.io/commit/985a333f3385bd82e0c25a3b00ca8fec12d44062).
