### ISSUE TITLE
Add note to Domain-Specific Languages

### ISSUE THREAD

**Issue by TimvdLippe** [TUDelft-IN4303-2016/TUDelft-IN4303-2016.github.io#15]
Given that this specific lecture was not present in the schedule of this year, it would be nice to add a note to https://tudelft-in4303-2016.github.io/lectures/introduction/domain-specific-languages.html stating that it is not required for the exam of this year.

**Comment by martijndwars** [comment]
I'd warmly welcome a PR that fixes this. Adding `{: .notice .notice-warning}` below a paragraph turns it into a note.
